### ISSUE TITLE
Update deprecated BinarySensorDevice component

### ISSUE THREAD

**Issue by 1h8fulkat** [kevinvincent/ha-wyzesense#142] opened 2020-05-21 19:01 UTC
```
2020-05-21 14:35:42 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for wyzesense which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-21 14:35:42 WARNING (MainThread) [homeassistant.components.binary_sensor] BinarySensorDevice is deprecated, modify WyzeSensor to extend BinarySensorEntity
```
Home assistant .110 has been throwing the following errors relating to the HA-WYZESENSE integration. Looks like the integration needs to update the component references.

**Comment by photinus** [comment] 2020-05-21 19:07
Duplicate of #139

**Closed by photinus** 2020-05-21 19:07 UTC
